version: '3'

env:
  CLUSTER_NAME: lab
  CLUSTER_CONFIG_PATH: ./cluster.yaml

tasks:
  init:
    cmds:
      - k3d cluster create $CLUSTER_NAME -c $CLUSTER_CONFIG_PATH
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
    desc:
      Initialize the k3d cluster, along with core ArgoCD
    silent: true
  destroy:
    cmds:
      - k3d cluster delete $CLUSTER_NAME
    desc:
      Destroy the k3d cluster
    silent: true