version: '3'

env:
  CLUSTER_CONFIG_PATH: ./cluster.yaml

tasks:
  init:
    cmds:
      - k3d cluster create -c $CLUSTER_CONFIG_PATH
      - kubectl apply -n portainer -f https://downloads.portainer.io/ce2-16/portainer.yaml
    desc:
      Initialize the k3d cluster
    silent: true
  destroy:
    cmds:
      - k3d cluster delete mycluster
    desc:
      Destroy the k3d cluster
    silent: true