version: '3'

env:
  CLUSTER_CONFIG_PATH: ./cluster.yaml

tasks:
  init:
    cmds:
      - k3d cluster create -c $CLUSTER_CONFIG_PATH
    desc:
      Initialize the k3d cluster
    silent: true
  destroy:
    cmds:
      - k3d cluster delete mycluster
    desc:
      Destroy the k3d cluster
    silent: true