apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: guestbook
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: guestbook
  source:
    repoURL: https://github.com/Looty/home-lab/
    targetRevision: argocd
    path: manifests/examples/app
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook